language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t vickypanchal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vickypanchal/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-905418258112"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
